version: '3.8'
# docker compose -p ikmimart_dev -f docker-compose.base.yml -f docker-compose.dev.yml up --build
services:
  app:
    volumes:
      - .:/app
    command: uv run -- uvicorn main:app --host 0.0.0.0 --port 80 --reload