# docker-compose.yml (Base configuration)
version: '3.8'
services:
  migrate:
    build: .
    command: python /app/migrations/migrate.py
    depends_on:
      - db
    networks:
      - ikmimart_network
    env_file:
      - .env.${ENV}

  app:
    build: .
    restart: always
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
      - redis
    networks:
      - ikmimart_network
    env_file:
      - .env.${ENV}
  
  db:
    image: postgres:17.4
    restart: always
    ports:
      - "${RDB_PORT}:5432"
    environment:
      - POSTGRES_USER=${RDB_USER}
      - POSTGRES_PASSWORD=${RDB_PASSWORD}
      - POSTGRES_DB=${RDB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ikmimart_network
  
  redis:
    image: redis:7.4
    restart: always
    command: ["redis-server", "--maxmemory", "2gb", "--maxmemory-policy", "allkeys-lru"]
    networks:
      - ikmimart_network

networks:
  ikmimart_network:
    driver: bridge


volumes:
  postgres_data:
    driver: local